Created Movies list with add form
mate-academy/react_movies-list-add-form pull request #1017
Opened 2022-10-25 12:39 UTC by Vladosik1337

[DEMO LINK](https://Vladosik1337.github.io/react_tabs/)

2022-10-26 11:00 UTC, imaksweb approved these changes
Nice work 👍

2022-11-01 20:16 UTC, Anna-Tkachenko requested changes

2022-11-01 20:16 UTC, Anna-Tkachenko commented on src/App.tsx
> +  const [movies, setMovies] = useState([...moviesFromServer]);
add type for useState

2022-11-01 20:16 UTC, Anna-Tkachenko commented on src/components/NewMovie/NewMovie.tsx
> +            }}
let's create form submit handler, not function on the submit form click

2022-11-01 20:16 UTC, Anna-Tkachenko commented on src/components/NewMovie/NewMovie.tsx
> +        onChange={setNewTitle}
change handlers should accept event object and set target value to the state, I don't see this functionality

2022-11-03 07:37 UTC, Anna-Tkachenko approved these changes
⭐️

2025-11-08 12:32 UTC, closed without merging