added inputs validation, set button work, movie adding implemented
mate-academy/react_movies-list-add-form pull request #1041
Opened 2022-10-26 17:15 UTC by SerhiiRomaniukWD

[DEMO LINK](https://serhiiromaniukwd.github.io/react_movies-list-add-form/)

2022-11-03 12:52 UTC, grafit-off approved these changes
LGTM ⭐

2022-11-03 16:07 UTC, sergii-nosachenko requested changes
You need to pass all tests before submitting PR

2022-11-08 07:50 UTC, Andr1yK approved these changes

2022-11-08 07:50 UTC, Andr1yK commented on src/components/NewMovie/NewMovie.tsx
> +
do u need this comment?)

2022-11-08 08:18 UTC, SerhiiRomaniukWD commented on src/components/NewMovie/NewMovie.tsx
> +
no)
I will delete it

2025-05-25 17:09 UTC, closed without merging