task solution
mate-academy/react_movies-list-add-form pull request #1046
Opened 2022-10-27 09:21 UTC by vladyslav-harkusha

[DEMO LINK](https://vladyslav-harkusha.github.io/react_movies-list-add-form/)

2022-10-27 12:01 UTC, Yuriy-Komolov approved these changes

2022-10-27 12:02 UTC, Yuriy-Komolov commented
Good Job!

2022-10-31 15:16 UTC, sergii-nosachenko requested changes
You need to add additional check if your fields consists of spaces only.
<img width="1440" alt="Screenshot 2022-10-31 at 17 15 53" src="https://user-images.githubusercontent.com/54940595/199042882-121a9303-7251-4dbb-86d1-5eb7f9949163.png">

2022-10-31 15:16 UTC, sergii-nosachenko commented on src/App.tsx
> +        <NewMovie onAdd={addMovie} />
```suggestion
        <NewMovie onAdd={addMovie} key={count} />
```
Move counter logic here. When you'll increase count your component will be created from scratch with default values and no errors.

2022-10-31 15:16 UTC, sergii-nosachenko commented on src/components/NewMovie/NewMovie.tsx
> +    setCount(current => current + 1);
```suggestion
```
Move setCount to parent component and use it in onAdd handler. You don't need to reset your form.

2022-10-31 15:16 UTC, sergii-nosachenko commented on src/components/NewMovie/NewMovie.tsx
> +        onChange={value => setTitle(value)}
```suggestion
        onChange={setTitle}
```
There is no event here. TextField component calls your handler with field value, so you don't need wrapper here.

Fix it everywhere.

2022-10-31 16:38 UTC, sergii-nosachenko approved these changes
Perfect 🔥

2024-10-30 18:44 UTC, closed without merging