solution
mate-academy/react_movies-list-add-form pull request #1071
Opened 2022-11-14 19:37 UTC by savchuksavchuk

[DEMO LINK](https://savchuksavchuk.github.io/react_movies-list-add-form/)

2022-11-15 15:34 UTC, loralevitska requested changes
hi, good job!  need some improvements
1. After lose focus url input show errors although inputs have value
![image](https://user-images.githubusercontent.com/70009205/201958883-bd0d5345-2316-4e9a-b3cc-ab7a6111fc57.png)

2022-11-15 15:34 UTC, loralevitska commented on src/components/NewMovie/NewMovie.tsx
> +  // eslint-disable-next-line
try to fix this linter rule and remove comment

2022-11-15 15:34 UTC, loralevitska commented on src/components/NewMovie/NewMovie.tsx
> +      }}
move this function to variable and use only function name for `onSubmit` property. Pay attention to the code style, fix it all over the filles

2022-11-19 17:09 UTC, savchuksavchuk commented
Hello. The error after unfocus ImageUrl and ImdbUrl - it's the url validation. I'm not shure, if it should work after unfocus or after submit but I added 'URL is invalid' error for this validation. I think i will be less confusing.
About regexp - I have no idea how to fix it. I tried to create regexp with new Regexp constructor - but it causes a lot of mistakes.

2022-11-20 10:22 UTC, TarasHoliuk commented
> Hello. The error after unfocus ImageUrl and ImdbUrl - it's the url validation. I'm not shure, if it should work after unfocus or after submit but I added 'URL is invalid' error for this validation. I think i will be less confusing. About regexp - I have no idea how to fix it. I tried to create regexp with new Regexp constructor - but it causes a lot of mistakes.

The possible solution is show to 'URL is invalid' if the input is also not empty

2022-11-20 10:22 UTC, TarasHoliuk requested changes

2022-11-20 10:22 UTC, TarasHoliuk commented on src/components/NewMovie/NewMovie.tsx
> +      onSubmit={(event) => handlerOnAdd(event)}
```suggestion
      onSubmit={handlerOnAdd}
```

2022-11-20 10:22 UTC, TarasHoliuk commented on src/components/TextField/TextField.tsx
> +  const [isPatternValid, setPatternValidation] = useState(true);
```suggestion
  const [isPatternValid, setIsPatternValid] = useState(true);
```

2022-11-20 10:22 UTC, TarasHoliuk commented on src/components/TextField/TextField.tsx
> +    setPatternValidation(() => onPatternValidation(value));
```suggestion
    setPatternValidation(onPatternValidation(value));
```

2022-11-20 22:21 UTC, savchuksavchuk commented
Hello. Now it works like this:
1. If url input is empty - 'URL is required' is showing
2. If url is not empty but it isn't correct 'URL is invalid' is showing

About the failed tests - I watched screenshot and it shows 'URL is invalid' error. I think tests are not provided for this validation but actually it works correctly.

Also I added the disabling for submit button if URL is invalid.

![image](https://user-images.githubusercontent.com/33101422/202926866-dd28b2cc-f0c1-4cc4-8da1-160811b12c00.png)
![image](https://user-images.githubusercontent.com/33101422/202926875-50a74bbd-a54d-4c20-827c-a520444334d9.png)

2022-11-21 19:01 UTC, polosanya approved these changes
Good job!

2024-12-28 10:48 UTC, closed without merging