Develop
mate-academy/react_movies-list-add-form pull request #1104
Opened 2022-12-03 09:10 UTC by Andriy-Shymkiv

2022-12-05 10:48 UTC, DanilSerzh approved these changes

2022-12-05 10:48 UTC, DanilSerzh commented on src/components/NewMovie/NewMovie.tsx
> +    && imgUrl.trim().length > 0
i think you can remove the length check

2022-12-07 08:57 UTC, denys-danyliuk requested changes
show an error if field filled with spaces
<img width="811" alt="Знімок екрана 2022-12-07 о 10 53 32" src="https://user-images.githubusercontent.com/106310796/206133790-e89117eb-68b6-48a3-b69e-e071921fc20e.png">
<img width="385" alt="Знімок екрана 2022-12-07 о 10 45 59" src="https://user-images.githubusercontent.com/106310796/206133786-724bbf77-2e2e-467e-8da0-37557664f872.png">

2022-12-07 08:57 UTC, denys-danyliuk commented on src/components/NewMovie/NewMovie.tsx
> +    setCount((prevCount) => prevCount + 1);
```suggestion
    event.preventDefault();
    
    onAdd(createdMovie);
    
    setTitle('');
    setDescription('');
    setImgUrl('');
    setImdbUrl('');
    setImdbId('');
    
    setCount((prevCount) => prevCount + 1);
```

2022-12-07 08:57 UTC, denys-danyliuk commented on src/components/NewMovie/NewMovie.tsx
> +    setImdbId('');
create function for clearing the form

2024-03-27 08:42 UTC, closed without merging