added solution
mate-academy/react_movies-list-add-form pull request #1109
Opened 2022-12-04 21:53 UTC by kryvets-vadym

[DEMO LINK](https://kryvets-vadym.github.io/react_movies-list-add-form/)

2022-12-06 09:20 UTC, denys-danyliuk requested changes
add an error when field filled with spaces, like title in this example
<img width="389" alt="Знімок екрана 2022-12-06 о 11 19 42" src="https://user-images.githubusercontent.com/106310796/205870900-a15bec1f-8648-4394-892e-d5e5cf69f23c.png">

2022-12-06 09:20 UTC, denys-danyliuk commented on src/App.tsx
> +  };
```suggestion
  const addMovie = (newMovie: Movie) => {
    setMovies([...currentMovies, newMovie]);
  };
```

2022-12-06 09:20 UTC, denys-danyliuk commented on src/components/NewMovie/NewMovie.tsx
> +  const submitApprove = title.trim().length > 0
```suggestion
  const isDisabled = !(title.trim()
```

2022-12-06 09:20 UTC, denys-danyliuk commented on src/components/NewMovie/NewMovie.tsx
> +    setImdbId('');
move this to a function

2022-12-14 06:13 UTC, Olexandr6 approved these changes

2024-01-15 14:01 UTC, closed without merging