New movie form added
mate-academy/react_movies-list-add-form pull request #1117
Opened 2022-12-05 13:58 UTC by Largoxoxo

[DEMO LINK](https://Largoxoxo.github.io/react_movies-list-add-form/)

2022-12-06 09:23 UTC, bohdan-stepanets approved these changes
Good job! 
But I can not help with extra task

2022-12-06 09:23 UTC, bohdan-stepanets commented on src/components/NewMovie/NewMovie.tsx
> +  const hasRequiredFields = (title.trim() && imgUrl.trim()
I think will be better to move all `&&` to new lines

2022-12-06 09:31 UTC, denys-danyliuk requested changes
add an error when you fields filled with spaces, like title on this examle
<img width="388" alt="Знімок екрана 2022-12-06 о 11 30 46" src="https://user-images.githubusercontent.com/106310796/205873493-9885865f-f898-4dab-95c4-5e364bbcae0b.png">

2022-12-06 09:31 UTC, denys-danyliuk commented on src/components/NewMovie/NewMovie.tsx
> +  const hasRequiredFields = (title.trim() && imgUrl.trim()
it's up to you

2022-12-08 08:24 UTC, denys-danyliuk approved these changes

2026-04-05 12:03 UTC, closed without merging