forQuestion
mate-academy/react_movies-list-add-form pull request #1124
Opened 2022-12-06 18:51 UTC by p-omogit-e

[DEMO LINK](https://p-omogit-e.github.io/react_movies-list-add-form/)

Реалізувала додавання нового фільму, проте коли додаю, то масив з фільмами змінюється, а сторінка не перемальовується.

2022-12-07 08:15 UTC, tetiana-ivanchenko requested changes
please, create PR only when your task is done, if you have any questions - feel free to aks it in the fe_chat2

2022-12-07 08:17 UTC, tetiana-ivanchenko reviewed
to automaticaly re-rendering page, when movies is changed - movies must to be used in the  useState

2022-12-07 19:30 UTC, p-omogit-e commented
> please, create PR only when your task is done, if you have any questions - feel free to aks it in the fe_chat2

Sorry, mentor in the fe_chat2 said me to do a pull

2022-12-08 08:33 UTC, tetiana-ivanchenko requested changes

2022-12-08 08:33 UTC, tetiana-ivanchenko commented on src/App.tsx
> +          }}
move it in the separate fucntion, and pass here just name of this function

2022-12-08 08:33 UTC, tetiana-ivanchenko commented on src/components/NewMovie/NewMovie.tsx
> +  onAdd?: (arg0: Movie) => void,
arg0? use more explicit naming

2022-12-08 08:33 UTC, tetiana-ivanchenko commented on src/components/NewMovie/NewMovie.tsx
>    // to reset touched status of all the `Field`s
remove comments

2022-12-08 08:33 UTC, tetiana-ivanchenko commented on src/components/NewMovie/NewMovie.tsx
> +  const [imdbId, setImdbId] = useState('');
it's ok, but just hint: you can use only one state, like object, whith values title, description, etc.

2022-12-08 08:33 UTC, tetiana-ivanchenko commented on src/components/NewMovie/NewMovie.tsx
> +  const cleanFields = () => {
```suggestion
  const clearFields = () => {
```

2022-12-08 08:33 UTC, tetiana-ivanchenko commented on src/components/NewMovie/NewMovie.tsx
> +            }}
move it in your addNewFilm fuction

2022-12-08 08:33 UTC, tetiana-ivanchenko commented on src/components/TextField/TextField.tsx
> +          onBlur={() => setToched(value === '' && (true))}
why do you need '&& true'?

2022-12-14 09:49 UTC, vlad-demchuk requested changes
check the previous comments
if you have any questions - feel free to ask in `fe_chat`

2022-12-14 09:49 UTC, vlad-demchuk commented on src/App.tsx
> +            addNewMovie(newMovie);
```suggestion
          onAdd={addNewMovie);
```

2022-12-14 09:49 UTC, vlad-demchuk commented on src/components/NewMovie/NewMovie.tsx
> +  const [imdbId, setImdbId] = useState('');
I agree, try to implement it instead to avoid creating states for each form field

2022-12-14 09:49 UTC, vlad-demchuk commented on src/components/NewMovie/NewMovie.tsx
> +            }}
+

2022-12-14 09:49 UTC, vlad-demchuk commented on src/components/NewMovie/NewMovie.tsx
> +    && Boolean(imdbUrl) && Boolean(imdbId);
it's not necessary to convert to Boolean since an empty string is `false`

2022-12-27 09:19 UTC, p-omogit-e commented on src/App.tsx
> +            addNewMovie(newMovie);
![image](https://user-images.githubusercontent.com/102521367/209643791-8a287d8f-599b-421c-bb7f-630b335ca120.png)

2022-12-27 12:32 UTC, TarasHoliuk requested changes
GJ! Almost done :+1: I've added 2 small suggestions - check it, please

2022-12-27 12:32 UTC, TarasHoliuk commented on src/components/NewMovie/NewMovie.tsx
> +    && (newFilm.imdbUrl) && (newFilm.imdbId);
```suggestion
    return newFilm.title && newFilm.imgUrl
    && newFilm.imdbUrl && newFilm.imdbId;
```

brackets are redundant here
also, trim all values here, because now I can fill each field with spaces only

2022-12-27 12:32 UTC, TarasHoliuk commented on src/App.tsx
> +            addNewMovie(newMovie);
Oh, I see. Create function using a function expression: `const addNewMovie = (newMovie: Movie) => { // function body }`. That will allow you to pass it as JSX prop

2022-12-31 11:55 UTC, SanyaBratashchuk approved these changes

2025-12-17 21:32 UTC, closed without merging