solution
mate-academy/react_movies-list-add-form pull request #1158
Opened 2023-01-05 10:51 UTC by olenitut

[DEMO LINK](https://olenitut.github.io/react_movies-list-add-form/)

2023-01-06 09:34 UTC, marina-tilniak requested changes

2023-01-06 09:34 UTC, marina-tilniak commented on src/App.tsx
> +  const [neededMovies, setNeededMovies] = useState([...moviesFromServer]);
```suggestion
  const [movies, setMovies] = useState([...moviesFromServer]);
```

2023-01-06 09:34 UTC, marina-tilniak commented on src/components/NewMovie/NewMovie.tsx
> +  onAdd: (movie: Movie)=>void
move typing for Props above

2023-01-06 09:34 UTC, marina-tilniak commented on src/components/NewMovie/NewMovie.tsx
> +    const key = target.id.slice(0, target.id.indexOf('-'));
just use imdbId

2023-01-06 09:34 UTC, marina-tilniak commented on src/components/TextField/TextField.tsx
> +  // generage a unique idonce on component load
:)

2023-01-07 12:01 UTC, Anastasiia-Svintsova requested changes
- I shouldn't be able to add movies with required empty fields

https://user-images.githubusercontent.com/99403198/211149539-cb461d39-dd8e-4b7f-94c2-f2d5f0ea234c.mov

2023-01-07 12:01 UTC, Anastasiia-Svintsova commented on src/components/NewMovie/NewMovie.tsx
> +  onAdd: (movie: Movie)=>void
```suggestion
  onAdd: (movie: Movie) => void
```

2023-01-07 12:01 UTC, Anastasiia-Svintsova commented on src/components/NewMovie/NewMovie.tsx
> +  const formIsValid = title && imdbId && imdbUrl && imgUrl;
use useMemo for this value, please

2023-01-08 12:15 UTC, mykhalenych requested changes

2023-01-08 12:15 UTC, mykhalenych commented on src/components/TextField/TextField.tsx
> +  const hasError = touched && required && !value.trim();
You added useMemo for formIsValid, add here as well

2023-01-08 12:15 UTC, mykhalenych commented on src/App.tsx
> +  const [movies, setMovies] = useState([...moviesFromServer]);
`[...moviesFromServer]` the same as `(moviesFromServer)`

2023-01-08 20:19 UTC, olenitut commented on src/components/TextField/TextField.tsx
> +  const hasError = touched && required && !value.trim();
I added it because the prev mentor asked for it, and only in that place((

2023-01-09 10:29 UTC, mykhalenych approved these changes

2023-10-18 14:19 UTC, closed without merging