solution
mate-academy/react_movies-list-add-form pull request #1170
Opened 2023-01-13 11:30 UTC by Fynkzia

[DEMO LINK](https://Fynkzia.github.io/react_movies-list-add-form/)

2023-01-16 09:33 UTC, TetKopot requested changes
gj! but the user should be able to add just a valid URL

2023-01-16 10:20 UTC, Fynkzia commented
> gj! but the user should be able to add just a valid URL

This is an optional task

2023-01-16 10:35 UTC, TetKopot approved these changes

2023-01-17 13:58 UTC, solaryasha requested changes

2023-01-17 13:58 UTC, solaryasha commented on src/components/NewMovie/NewMovie.tsx
> +  };
Let's use `useCallback` for render optimisation, because you are passing these callbacks to another components

2023-01-18 07:36 UTC, solaryasha approved these changes
👍

2024-04-08 10:09 UTC, closed without merging