soltuion
mate-academy/react_movies-list-add-form pull request #1362
Opened 2023-03-30 11:05 UTC by Nordexz

[DEMO LINK](https://nordexz.github.io/react_movies-list-add-form/)

2023-03-31 12:36 UTC, vladyslav-mosor approved these changes
Good job!

2023-04-04 10:11 UTC, sergii-nosachenko requested changes

2023-04-04 10:11 UTC, sergii-nosachenko commented on src/components/NewMovie/NewMovie.tsx
> +  function clear() {
Be more specific in function name

2023-05-06 10:13 UTC, And678 requested changes
Don't forget to test your code before pushing to github, everything is great, but you intoduced a critical bug on last commit. Currently, the `Add` button is disabled if **all** of the fields are correct :smiley:

2023-05-06 10:14 UTC, And678 commented
Also, check the tests, they are failing because of this

2025-09-29 20:22 UTC, closed without merging