add task solution
mate-academy/react_movies-list-add-form pull request #1534
Opened 2023-06-07 16:24 UTC by NickMitchell61

[DEMO LINK](https://NickMitchell61.github.io/react_movies-list-add-form/)

2023-06-08 10:55 UTC, ruslanpashkov requested changes

2023-06-08 10:55 UTC, ruslanpashkov commented on src/App.tsx
> +  const handleAddMovie = (movie: Movie) => {
it's not a handler, so you don't need `handle` keyword here
```suggestion
  const addMovie = (movie: Movie) => {
```

2023-06-08 10:55 UTC, ruslanpashkov commented on src/components/NewMovie/NewMovie.tsx
> +  onAdd: (movie: Movie) => void,
```suggestion
  onAdd: (movie: Movie) => void;
```

2023-06-08 10:55 UTC, ruslanpashkov commented on src/components/NewMovie/NewMovie.tsx
> +    setImdbId('');
```suggestion
    setFormData(initialFormData);
```

2023-06-08 10:55 UTC, ruslanpashkov commented on src/components/NewMovie/NewMovie.tsx
> +    setCount(count + 1);
we change our current state based on previous state, let's use functional `setCount` here

2023-06-08 10:55 UTC, ruslanpashkov commented on src/components/NewMovie/NewMovie.tsx
> +  }, [title, imgUrl, imdbUrl, imdbId]);
what if the fields are only filled with spaces?

also we can create separate variable for it and pass negation of this value to `disabled` attribute

2023-06-12 05:14 UTC, silchyn requested changes
Form can be submitted several times in a row with no values entered

2023-06-22 08:21 UTC, silchyn requested changes
When all values are spaces, submit button is disabled, but no validation message is shown
<img width="394" alt="image" src="https://github.com/mate-academy/react_movies-list-add-form/assets/30828805/0a0d4f25-46d8-4a75-ab40-5b95b9b8c5a1">

2023-06-22 09:21 UTC, And678 approved these changes
Good work, approve :heavy_check_mark:

2023-07-05 08:03 UTC, closed without merging