Solution
mate-academy/react_movies-list-add-form pull request #1550
Opened 2023-06-21 16:36 UTC by bohdan-mykhailenko

[DEMO LINK](https://bohdan-mykhailenko.github.io/react_movies-list-add-form/)

2023-06-22 08:18 UTC, silchyn requested changes
- I can submit a form with a title consisting of spaces
- Can we show the URL validation error under the field like the required validation error?

2023-06-26 09:15 UTC, dffUqp requested changes
LGTM:fire: but needs a few fixes:upside_down_face:

2023-06-26 09:15 UTC, dffUqp commented on src/components/NewMovie/NewMovie.tsx
> +  const pattern = /^((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=+$,\w]+@)?[A-Za-z0-9.-]+|(?:www\.|[-;:&=+$,\w]+@)[A-Za-z0-9.-]+)((?:\/[+~%/.\w-_]*)?\??(?:[-+=&;%@,.\w_]*)#?(?:[,.!/\\\w]*))?)$/;
let's create a helper function for checking our value.

something like: 
```jsx
const validateUrl = (value) => {
  const pattern = /^((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=+$,\w]+@)?[A-Za-z0-9.-]+|(?:www\.|[-;:&=+$,\w]+@)[A-Za-z0-9.-]+)((?:\/[+~%/.\w-_]*)?\??(?:[-+=&;%@,.\w_]*)#?(?:[,.!/\\\w]*))?)$/;
  
  return pattern.test(value)
}
 ```

2023-06-26 09:15 UTC, dffUqp commented on src/components/NewMovie/NewMovie.tsx
> +  const isFormFilled = title && imgUrl && imdbUrl && imdbId;
I'm still can submit a form with a title consisting of spaces. 

add `.trim()` to prevent this behavior

2023-06-26 09:16 UTC, dffUqp commented on src/components/NewMovie/NewMovie.tsx
> +  const isFormFilled = title && imgUrl && imdbUrl && imdbId;
![image](https://github.com/mate-academy/react_movies-list-add-form/assets/96138503/88c1180c-4a15-4d07-aaa3-b91d54983cd7)

2023-06-27 08:57 UTC, bohdan-mykhailenko commented on src/components/NewMovie/NewMovie.tsx
> +  const isFormFilled = title.trim() && imgUrl && imdbUrl && imdbId.trim();
I suit checking of url values in my validateUrl function

2023-06-27 09:00 UTC, bohdan-mykhailenko commented on src/components/NewMovie/NewMovie.tsx
> +      .toLowerCase()
I remove extra spaces to avoid a mess in the text fields

2023-06-27 09:45 UTC, dffUqp approved these changes
:fire:

2023-06-27 09:45 UTC, dffUqp commented on src/App.tsx
> +    setMovies([...movies, movie]);
good practice to use a callback when we need a prevState
```suggestion
    setMovies((prevMovies) => [...prevMovies, movie]);
```

2023-06-27 09:47 UTC, dffUqp commented on src/components/NewMovie/NewMovie.tsx
> +            <h5 style={{ color: 'red' }}>
try to avoid using `inline-styles`

2024-08-02 22:07 UTC, closed without merging