Solution
mate-academy/react_movies-list-add-form pull request #1563
Opened 2023-06-22 16:03 UTC by amashutikov

[DEMO LINK](https://amashutikov.github.io/react_movies-list-add-form/)

2023-06-22 18:15 UTC, dinaminahi requested changes
Good job 👍 
Few fixes needed

2023-06-22 18:15 UTC, dinaminahi commented on src/App.tsx
> +  };
```suggestion
  const addMovie = (movie: Movie) => {
    setVivsibleMovies(prevMovies => [...prevMovies, movie]);
  };
```

2023-06-22 18:15 UTC, dinaminahi commented on src/App.tsx
> +  const [visibleMovies, setVivsibleMovies] = useState(moviesFromServer);
```suggestion
  const [visibleMovies, setVisibleMovies] = useState(moviesFromServer);
```

2023-06-22 18:15 UTC, dinaminahi commented on src/components/NewMovie/NewMovie.tsx
> +  const [imdbId, setImdbId] = useState('');
Instead of creating so many states, let's create one that will be object `formState` and will contain all fields as properties:
`const [formState, setFormState] = useState({ title: "", description: "", imgUrl: "", ... });`

2023-06-22 18:15 UTC, dinaminahi commented on src/components/NewMovie/NewMovie.tsx
> +  const submitButtonIsDisabled = (
```suggestion
  const isSubmitButtonDisabled = (
```

2023-06-26 08:18 UTC, 33Orange requested changes
Almost done

2023-06-26 08:18 UTC, 33Orange commented on src/components/NewMovie/NewMovie.tsx
>    // to reset touched status of all the `Field`s
Remove redundant comments

2023-06-26 08:42 UTC, 33Orange approved these changes
Well done

2023-11-29 15:51 UTC, closed without merging