solution
mate-academy/react_movies-list-add-form pull request #1627
Opened 2023-07-12 12:53 UTC by DanyloPasko

[DEMO LINK](https://DanyloPasko.github.io/react_movies-list-add-form/)

2023-07-12 13:50 UTC, anastasiiavorobiova requested changes
Great start! Added a few comments to fix

2023-07-12 13:50 UTC, anastasiiavorobiova commented on src/test/validUrl.ts
> +export const isValidUrl = (value: string) => {
There is no type annotation for the return value of the function. It is recommended to always annotate the return type of functions for better readability and error avoidance.

2023-07-12 13:50 UTC, anastasiiavorobiova commented on src/components/NewMovie/NewMovie.tsx
> +        setImbdUrlError('Invalid imbd URL');
The error message 'Invalid imbd URL' seems to have a typo. It should be 'Invalid imdb URL'.

2023-07-12 13:50 UTC, anastasiiavorobiova commented on src/components/NewMovie/NewMovie.tsx
> +    handleReset();
You should handle resetting the form after the new movie has been successfully added. In the current implementation, you are clearing the form values before the onAdd function is called. This can result in the addition of an empty movie object if onAdd is asynchronous and takes more time to execute.

2023-07-12 13:50 UTC, anastasiiavorobiova commented on src/components/NewMovie/NewMovie.tsx
> +  const [count, setCount] = useState(0);
The 'count' state is initialized but it doesn't seem to be used anywhere in the component. If it's not used, consider removing it to avoid unnecessary state management.

2023-07-12 13:50 UTC, anastasiiavorobiova commented on src/components/TextField/TextField.tsx
> +  onChange = () => { },
There is an extra space between the arrow function brackets, this is not an error but it's considered as a bad practice.

2023-07-12 13:50 UTC, anastasiiavorobiova commented on src/components/TextField/TextField.tsx
> +  const hasError = (touched && required && !value);
The additional parentheses around the boolean expression in 'hasError' are unnecessary and can be removed.

2023-07-12 14:41 UTC, DanyloPasko commented on src/components/NewMovie/NewMovie.tsx
> +  const [count, setCount] = useState(0);
counter used

2023-07-13 06:48 UTC, OleziO requested changes

2023-07-13 06:48 UTC, OleziO commented on src/test/validUrl.ts
> +  const pattern = new RegExp(/^((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=+$,\w]+@)?[A-Za-z0-9.-]+|(?:www\.|[-;:&=+$,\w]+@)[A-Za-z0-9.-]+)((?:\/[+~%/.\w-_]*)?\??(?:[-+=&;%@,.\w_]*)#?(?:[,.!/\\\w]*))?)$/);
Split regexp by a few line and remove rule disabling.
![image](https://github.com/mate-academy/react_movies-list-add-form/assets/56752562/f91aea45-38f9-4192-85f0-3348585fb964)

2023-07-13 14:23 UTC, anastasiiavorobiova approved these changes
Great solution!

2025-06-13 14:20 UTC, closed without merging