Develop
mate-academy/react_movies-list-add-form pull request #1636
Opened 2023-07-15 13:38 UTC by AndriiYelieva

[DEMO LINK](https://AndriiYelieva.github.io/react_movies-list-add-form/)

2023-07-16 09:05 UTC, OleziO requested changes
Add string trim to avoid creating the empty movie.
![image](https://github.com/mate-academy/react_movies-list-add-form/assets/56752562/2ed1fdb2-3fd4-4155-b93d-4ca411e0794b)

2023-07-16 09:05 UTC, OleziO commented on src/components/TextField/TextField.tsx
> +          onBlur={handleFieldBlur} // Fixed: Removed unnecessary arrow function wrapper
Remove all comments from the code.

2023-07-16 09:05 UTC, OleziO commented on src/services/checkIsValidUrl.ts
> +
Split it by a few lines and remove the rule disabling.
![image](https://github.com/mate-academy/react_movies-list-add-form/assets/56752562/3db74c0c-7e47-4d82-8292-cf8a22c14ac5)

2023-07-16 09:05 UTC, OleziO commented on tsconfig.json
> +}
Add an empty line at the end of the file.

2023-07-17 12:02 UTC, IvanFesenko requested changes
Check this case
https://github.com/mate-academy/react_movies-list-add-form/assets/61904995/acd9fd2c-b158-44af-923a-95d1726b0530
![2023-07-17_15h01_29](https://github.com/mate-academy/react_movies-list-add-form/assets/61904995/ef6d17ae-7a09-4b68-9c06-b04c2a35eca6)

2023-07-18 07:24 UTC, etojeDenys approved these changes

2024-09-12 11:01 UTC, closed without merging