MovieListForm
mate-academy/react_movies-list-add-form pull request #1731
Opened 2023-08-15 11:46 UTC by Dmytro-Tymchenko

[DEMO LINK](https://Dmytro-Tymchenko.github.io/react_movies-list-add-form/)

2023-08-15 16:30 UTC, maxim2310 requested changes
Almost there) Just one more thing needs to be fixed
 you dont validate Imdb URL
![image](https://github.com/mate-academy/react_movies-list-add-form/assets/96265844/1fd6a194-e98e-4dde-a25a-4552e6899d38)

2023-08-15 16:30 UTC, maxim2310 commented on src/components/NewMovie/NewMovie.tsx
> +  const [imdbId, setImdbId] = useState('');
would be nice to create a one obj instead of this

2023-08-15 16:30 UTC, maxim2310 commented on src/components/NewMovie/NewMovie.tsx
> +        }}
check out this in all places 
```suggestion
        onChange={setTitle}
```

2023-08-17 09:55 UTC, VitaliyBondarenko1982 approved these changes
Looks good

2025-08-08 08:13 UTC, closed without merging