done
mate-academy/react_movies-list-add-form pull request #1746
Opened 2023-08-22 16:50 UTC by maxonshev

https://maxonshev.github.io/react_movies-list-add-form/

2023-08-22 17:49 UTC, etojeDenys requested changes
i can just write spaces in the title field and add a new movie, let's fix this case with `trim`

2023-08-22 17:49 UTC, etojeDenys commented on src/components/NewMovie/NewMovie.tsx
> +  const [imdbId, setImdbId] = useState('');
we can combine it in one useState
```
const [newMovie, setNewMovie] = useState({
  title: '',
  ...
})
```

now we can also create only one handle function for all fields
```
const handleChange = (e: ...) => {
  const {name, value} = e.target;
  setMovie((prevMovie) => ({...prevMovie, [name]: value}))
}
```

don't forget to specify name attr to input in TextField

2023-08-22 17:49 UTC, etojeDenys commented on src/components/NewMovie/NewMovie.tsx
> +        onChange={newDescription => setDescription(newDescription)}
```suggestion
        onChange={setDescription}
```

2023-08-25 12:39 UTC, IvanFesenko approved these changes
Well done

2023-08-25 12:39 UTC, IvanFesenko commented on src/components/NewMovie/NewMovie.tsx
> +  };
To avoid code duplicating you can create varaible with empty object and use it 
```
const EMPTY_MOVIE = {
    title: '',
    description: '',
    imgUrl: '',
    imdbUrl: '',
    imdbId: ''
};
```
```suggestion
  const [newMovie, setNewMovie] = useState(EMPTY_MOVIE );

  const handleChange = (name: string, value: string) => {
    setNewMovie({
      ...newMovie,
      [name]: value,
    });
  };

  const reset = () => {
    setNewMovie(EMPTY_MOVIE);
  };
```

2025-03-07 10:39 UTC, closed without merging