implement adding imdb films using forms
mate-academy/react_movies-list-add-form pull request #1767
Opened 2023-09-05 16:45 UTC by Koliras

[DEMO LINK](https://Koliras.github.io/react_movies-list-add-form/)

2023-09-05 17:48 UTC, DenisChakhalian approved these changes
good job!

2023-09-07 08:45 UTC, Moroz-Dmytro requested changes
Good work 👍 
But let's make your solution better
Also, if you have free time try to implement optional task

2023-09-07 08:45 UTC, Moroz-Dmytro commented on src/App.tsx
> +    setMovies([...movies, movie]);
If you change state based on previous value, better to use callback for this

2023-09-07 08:45 UTC, Moroz-Dmytro commented on src/components/NewMovie/NewMovie.tsx
> +  const [imdbId, setImdbId] = useState('');
Let's refactor your solution and use only 1 state for all form fields
It will be next object`{ title: '', description: '', ...}`

2023-09-08 07:03 UTC, Moroz-Dmytro requested changes
Please, fix demo link, I am not able to check UI

2023-09-08 07:03 UTC, Moroz-Dmytro commented on src/App.tsx
> +  const onAdd = (movie: Movie) => {
```suggestion
  const handleAddMovie = (movie: Movie) => {
```

2023-09-08 07:03 UTC, Moroz-Dmytro commented on src/components/NewMovie/NewMovie.tsx
> +    title: '', description: '', imgUrl: '', imdbUrl: '', imdbId: '',
Create constant for default value

2023-09-08 07:03 UTC, Moroz-Dmytro commented on src/components/NewMovie/NewMovie.tsx
> +      title: '', description: '', imgUrl: '', imdbUrl: '', imdbId: '',
Here you can reuse your created constant with default values

2023-09-08 07:03 UTC, Moroz-Dmytro commented on src/components/NewMovie/NewMovie.tsx
> +    });
```suggestion
    onAdd(movie);
```

2023-09-08 07:03 UTC, Moroz-Dmytro commented on src/components/NewMovie/NewMovie.tsx
> +  };
```suggestion
  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = event.target;
  
    setFormData((prevState) => ({
      ...prevState,
      [name]: value,
    }));
  };
```

2023-09-08 07:03 UTC, Moroz-Dmytro commented on src/components/NewMovie/NewMovie.tsx
> +        onChange={(event) => handleInputChange('title', event)}
```suggestion
        onChange={handleInputChange}
```

2023-09-08 07:03 UTC, Moroz-Dmytro commented on src/components/NewMovie/NewMovie.tsx
> +        onChange={(event) => handleInputChange('title', event)}
The same in all other places

2023-09-08 11:07 UTC, BudnikOleksii approved these changes
Good job 👍

2023-09-08 11:07 UTC, BudnikOleksii commented on src/App.tsx
> +  const onAdd = (movie: Movie) => {
> 
The handler's name isn't fixed. Article about naming convention: https://javascript.plainenglish.io/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364

2024-12-16 14:45 UTC, closed without merging