solution
mate-academy/react_movies-list-add-form pull request #1779
Opened 2023-09-06 14:09 UTC by Valentyn-Bilyk

[DEMO LINK](https://Valentyn-Bilyk.github.io/react_movies-list-add-form/)

2023-09-06 15:08 UTC, Denys14Samoilenko approved these changes
Good work!! 🥇

2023-09-07 08:39 UTC, Moroz-Dmytro requested changes
GJ 👍 
But let's refactor your solution
Also, if you have free time you can try to do optional task

2023-09-07 08:39 UTC, Moroz-Dmytro commented on src/components/NewMovie/NewMovie.tsx
> +  const [description, setDescription] = useState('');
Try to refactor your solution and to use only 1 state here
P.S. It will be next object `{ title: '', description: '', ...}`

2023-09-07 08:39 UTC, Moroz-Dmytro commented on src/components/NewMovie/NewMovie.tsx
> +  const isDisabled = !title || !imgUrl || !imdbUrl || !imdbId;
```suggestion
  const isAddButtonDisabled = !title || !imgUrl || !imdbUrl || !imdbId;
```

2023-09-07 08:39 UTC, Moroz-Dmytro commented on src/components/NewMovie/NewMovie.tsx
> +  const handleAdd = (event: React.FormEvent) => {
```suggestion
  const handleSubmit = (event: React.FormEvent) => {
```

2023-09-07 08:39 UTC, Moroz-Dmytro commented on src/components/NewMovie/NewMovie.tsx
> +    setCount((prewCount) => prewCount + 1);
```suggestion
    setCount((prevCount) => prevCount + 1);
```

2023-09-11 20:59 UTC, Valentyn-Bilyk commented on src/components/NewMovie/NewMovie.tsx
> +  const [description, setDescription] = useState('');
-(

2023-09-12 07:59 UTC, Moroz-Dmytro requested changes
I'm able to add movie with empty fields(just spaces entered), let's fix this

<img width="397" alt="image" src="https://github.com/mate-academy/react_movies-list-add-form/assets/86789161/be491e3b-3637-4b2a-bc88-0930593ce522">

2023-09-12 07:59 UTC, Moroz-Dmytro commented on src/components/NewMovie/NewMovie.tsx
> +        onChange={(newValue) => setTitle(newValue)}
```suggestion
        onChange={setTitle}
```

2023-09-12 07:59 UTC, Moroz-Dmytro commented on src/components/NewMovie/NewMovie.tsx
> +        onChange={(newValue) => setTitle(newValue)}
Same in other places

2023-09-15 16:38 UTC, BudnikOleksii approved these changes
Good job 👍

2026-01-24 21:36 UTC, closed without merging