add functional for movies form
mate-academy/react_movies-list-add-form pull request #1792
Opened 2023-09-06 18:22 UTC by rostyslav48

[DEMO LINK](https://rostyslav48.github.io/react_movies-list-add-form/)

2023-09-07 12:03 UTC, olegpaunov approved these changes
Looks good 🔥

2023-09-08 06:53 UTC, Moroz-Dmytro requested changes
Now I'm able to add movie with empty fields, let's fix this 😉 

<img width="398" alt="image" src="https://github.com/mate-academy/react_movies-list-add-form/assets/86789161/c88ade44-e120-4c85-8ee5-26a05c316003">

2023-09-08 06:53 UTC, Moroz-Dmytro commented on src/App.tsx
> +        <NewMovie onAdd={(movie: Movie) => addMovie(movie)} />
```suggestion
        <NewMovie onAdd={addMovie} />
```

2023-09-08 06:53 UTC, Moroz-Dmytro commented on src/components/NewMovie/NewMovie.tsx
> +  const [imdbId, setImdbId] = useState('');
Let's refactor your solution and use only 1 state for all form fields
It will be next object`{ title: '', description: '', ...}`

2023-09-08 09:11 UTC, rostyslav48 commented on src/components/NewMovie/NewMovie.tsx
> +  const [imdbId, setImdbId] = useState('');
I have reduced number of `states`. However Anna said that it is not a good practice to do 1 state to all fields, is it?

2023-09-08 12:52 UTC, roman-mirzoian approved these changes
Well done 👍

2025-08-31 20:05 UTC, closed without merging