dev
mate-academy/react_movies-list-add-form pull request #188
Opened 2021-01-25 09:28 UTC by Layrovell

[DEMO LINK](https://Layrovell.github.io/react_movies-list-add-form/)

2021-01-27 11:53 UTC, dtsehelnyk approved these changes

2021-01-27 11:53 UTC, dtsehelnyk commented on src/components/NewMovie/NewMovie.js
> +      if (check && this.state.buttonDisabled) {
`this.state.buttonDisabled` тоже можно было бы деструктурировать

2021-01-27 11:53 UTC, dtsehelnyk commented on src/components/NewMovie/NewMovie.js
> +    const validUrl = /^((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=+$,\w]+@)?[A-Za-z0-9.-]+|(?:www\.|[-;:&=+$,\w]+@)[A-Za-z0-9.-]+)((?:\/[+~%/.\w-_]*)?\??(?:[-+=&;%@.\w_]*)#?(?:[.!/\\\w]*))?)$/;
Думаю, что это можно было бы записать как внешнюю переменную, чтобы не дублировать

2021-01-27 13:45 UTC, aliceblunt8 requested changes

2021-01-27 13:45 UTC, aliceblunt8 commented on src/components/NewMovie/NewMovie.js
> +  validationMovie = (e) => {
```suggestion
  handleSubmit = (e) => {
```

2021-01-27 13:45 UTC, aliceblunt8 commented on src/components/NewMovie/NewMovie.js
> +          {imdbId.length > 0 ? <span className="green-text">✓</span> : ''}
```suggestion
          {imdbId.length > 0 && <span className="green-text">✓</span>}
```

2021-01-27 13:45 UTC, aliceblunt8 commented on src/components/NewMovie/NewMovie.js
> +  componentDidUpdate() {
why you do this in componentDidUpdate?

>validate controls values on blur

2021-01-27 13:45 UTC, aliceblunt8 commented on src/components/NewMovie/NewMovie.js
> +        buttonDisabled: true,
```suggestion
        buttonDisabled: false,
```

2021-01-27 13:45 UTC, aliceblunt8 commented on src/components/NewMovie/NewMovie.js
> +          {title.length > 0 ? <span className="green-text">✓</span> : ''}
```suggestion
          {title.length > 0 && <span className="green-text">✓</span>}
```

2021-01-27 13:45 UTC, aliceblunt8 commented on src/components/NewMovie/NewMovie.js
> +          {description.length > 0 ? <span className="green-text">✓</span> : ''}
same

2021-01-27 13:45 UTC, aliceblunt8 commented on src/components/NewMovie/NewMovie.scss
> +  //outline: 3px dashed indigo;
delete comments

2021-01-27 16:30 UTC, aliceblunt8 requested changes

2021-01-27 16:30 UTC, aliceblunt8 commented on src/components/NewMovie/NewMovie.js
> +  componentDidUpdate() {
fix this

2021-01-27 16:30 UTC, aliceblunt8 commented on src/components/NewMovie/NewMovie.js
> +  componentDidUpdate() {
let's validate values on submit

2021-01-28 14:51 UTC, aliceblunt8 approved these changes

2021-01-28 14:51 UTC, aliceblunt8 commented on src/components/NewMovie/NewMovie.js
> +    const check = validUrl.test(imgUrl) && validUrl.test(imdbUrl);
```suggestion
    const isValid = validUrl.test(imgUrl) && validUrl.test(imdbUrl);
```

2021-01-28 14:51 UTC, aliceblunt8 commented on src/components/NewMovie/NewMovie.js
> +    if (check) {
```suggestion
    if (isValid) {
```

2021-01-28 14:51 UTC, aliceblunt8 commented on src/components/NewMovie/NewMovie.js
> +      if (check) {
```suggestion
      if (isValid) {
```

2024-04-30 01:14 UTC, closed without merging