movies list
mate-academy/react_movies-list-add-form pull request #1882
Opened 2023-10-02 17:38 UTC by stunnerboyone

[DEMO LINK](https://stunnerboyone.github.io/react_movies-list-add-form/)

2023-10-02 17:42 UTC, etojeDenys requested changes
let's show the error when I try to fill inputs with spaces

2023-10-02 17:42 UTC, etojeDenys commented on src/components/NewMovie/NewMovie.tsx
> +  const [imdbId, setImdbId] = useState('');
we can combine it in one useState
```
const [newMovie, setNewMovie] = useState({
  title: '',
  ...
})
```

now we can also create only one handle function for all fields
```
const handleChange = (e: ...) => {
  const {name, value} = e.target;
  setMovie((prevMovie) => ({...prevMovie, [name]: value}))
}
```

don't forget to specify name attr to input in TextField

2023-10-03 08:18 UTC, anastasiia-tilikina requested changes
just one more small fix

2023-10-03 08:18 UTC, anastasiia-tilikina commented on src/components/NewMovie/NewMovie.tsx
> +    });
let's create a var for example `initialState` and reuse it to avoid code duplication

2023-10-03 09:02 UTC, anastasiia-tilikina approved these changes
Well done!

2023-11-21 19:23 UTC, closed without merging