my code doesnt work, help!
mate-academy/react_movies-list-add-form pull request #1977
Opened 2023-11-15 09:17 UTC by OPTIMISTIXX

(https://OPTIMISTIXX.github.io/react_movies-list-add-form/)

2023-11-15 09:27 UTC, etojeDenys approved these changes
awesome

2023-11-15 09:40 UTC, volodymyr-soltys97 requested changes
Doesn't work

2023-11-15 12:45 UTC, lerastarynets reviewed
I can now add whose fields consist of white spaces only, pls fix

2023-11-15 12:45 UTC, lerastarynets commented on src/components/NewMovie/NewMovie.tsx
> +               || imdbUrl.length === 0 || imdbId.length === 0}
```suggestion
            disabled={!title.length
               || !imgUrl.length
               || !imdbUrl.length || !imdbId.length}
```
also pls consider moving this expression to separate const and using here

2023-11-15 12:45 UTC, lerastarynets requested changes
.

2023-11-16 18:18 UTC, etojeDenys approved these changes
good job

2025-08-04 16:12 UTC, closed without merging