add form
mate-academy/react_movies-list-add-form pull request #2062
Opened 2023-12-22 08:49 UTC by Vlad4567

- [DEMO LINK](https://Vlad4567.github.io/react_movies-list-add-form/)

2023-12-22 08:54 UTC, maxim2310 requested changes
Great job overall! Just couple tiny things needs to be fixed before approval)

2023-12-22 08:54 UTC, maxim2310 commented on src/components/NewMovie/NewMovie.tsx
> +  const [imdbId, setImdbId] = useState('');
better to use one state with object

2023-12-22 08:54 UTC, maxim2310 commented on src/components/NewMovie/NewMovie.tsx
> +    setImdbId('');
and need to create initial movie object for using here for clean form and as initial value in state

2023-12-22 10:17 UTC, OleziO requested changes
After filling out the form, the film is not added to the list of films

2023-12-22 10:17 UTC, OleziO commented on src/components/TextField/TextField.tsx
>    // generage a unique id once on component load
Remove all comments from the code

2023-12-23 14:41 UTC, VitaliyBondarenko1982 requested changes
As user I filled form. See some fields with red color but without any validation error. Can add film. But after click nothing happened.
Please check your logic (show some error text if some field is invalid, keep add button disabled if some field is invalid).
![chrome-capture-2023-12-23](https://github.com/mate-academy/react_movies-list-add-form/assets/33029864/ef5d5643-7ac5-4280-925c-679038c0ef95)

2023-12-23 15:48 UTC, volodymyr-soltys97 approved these changes
Great work 🔥

2026-08-06 08:05 UTC, closed without merging