Solution
mate-academy/react_movies-list-add-form pull request #2102
Opened 2024-01-16 18:57 UTC by YevhenOstrovskiy

[DEMO LINK](https://YevhenOstrovskiy.github.io/react_movies-list-add-form/)

2024-01-16 21:21 UTC, sasholk approved these changes
Nice Job Mate!! 🔥🔥🔥🔥
But make some changes

2024-01-16 21:21 UTC, sasholk commented on src/components/NewMovie/NewMovie.tsx
> +            }}
better make handler if callback more than 1 row

2024-01-16 21:21 UTC, sasholk commented on src/components/NewMovie/NewMovie.tsx
> +  const isDisabled = !(title && imgUrl && imdbUrl && imdbId);
add method `trim` cuz your form works with only spaces

2024-01-18 09:16 UTC, olya-shyian requested changes
Good work!💪

Unfortunately, there is a bug. If you add some space to each input then the 'add' button will no longer be disabled so you can create an empty movie and add to the list.

![image](https://github.com/mate-academy/react_movies-list-add-form/assets/91946036/0517fadf-292b-4638-8a07-a17004875db5)

Please, try to fix it

2024-01-18 09:16 UTC, olya-shyian commented on src/components/NewMovie/NewMovie.tsx
> +            }}
I would recommend put all this logic to `handleAddForm` function

2024-01-22 13:44 UTC, olya-shyian approved these changes
Nice🌸

2024-09-01 16:45 UTC, closed without merging