add solution
mate-academy/react_movies-list-add-form pull request #2183
Opened 2024-03-04 21:35 UTC by dmitruz

[DEMO LINK](https://dmitruz.github.io/react_movies-list-add-form/)

2024-03-05 07:12 UTC, etojeDenys requested changes
https://github.com/mate-academy/react_movies-list-add-form/assets/70220667/26b3a25d-8075-499a-bae6-f431a484d4fe

looks broken

2024-03-05 07:12 UTC, etojeDenys commented on src/components/NewMovie/NewMovie.tsx
> +  useMemo(() => {
please, read or ask in the chat how we need to use the useMemo, it's incorrect

https://react.dev/reference/react/useMemo#usage

2024-03-05 07:12 UTC, etojeDenys commented on src/components/NewMovie/NewMovie.tsx
> +  const [isValid, setIsValid] = useState(false);
it can be the simple var instead of the state

2024-03-05 07:12 UTC, etojeDenys commented on src/components/NewMovie/NewMovie.tsx
> +          updateFormValue('description', newValue);
probably should be title as the key here

2024-03-05 07:12 UTC, etojeDenys commented on src/components/NewMovie/NewMovie.tsx
> +          updateFormValue('imgUrl', newValue);
fix it everywhere

2024-03-05 19:40 UTC, etojeDenys requested changes

2024-03-05 19:40 UTC, etojeDenys commented on src/components/NewMovie/NewMovie.tsx
> +  const [imdbId, setImdbID] = useState('');
we can combine it in one useState
```
const [newMovie, setNewMovie] = useState({
  title: '',
  ...
})
```

now we can also create only one handle function for all fields
```
const handleChange = (e: ...) => {
  const {name, value} = e.target;
  setMovie((prevMovie) => ({...prevMovie, [name]: value}))
}
```

don't forget to specify name attr to input in TextField

2024-03-05 19:40 UTC, etojeDenys commented on src/components/NewMovie/NewMovie.tsx
> +  const [imdbId, setImdbID] = useState('');
feel free to ask about it in the chat

2024-03-05 19:40 UTC, etojeDenys commented on src/components/TextField/TextField.tsx
> +        <p className="help is-danger">{`${label} is required`}</p>
specify the error name, you probably want to say that the label is invalid

2024-03-06 07:42 UTC, etojeDenys requested changes
1. i can add the movie only with spaces, better to fix it
<img width="365" alt="image" src="https://github.com/mate-academy/react_movies-list-add-form/assets/70220667/46948100-6a12-4e22-8946-32ca64474468">

2. why do you remove the validation logic

2024-03-07 07:44 UTC, volodymyr-soltys97 requested changes
Almost done!
Need to use trim() for the links
<img width="401" alt="image" src="https://github.com/mate-academy/react_movies-list-add-form/assets/64750958/0223bddd-f75b-4c02-b4d6-c7b9801ddbbc">
<img width="407" alt="image" src="https://github.com/mate-academy/react_movies-list-add-form/assets/64750958/5db5c16d-c9ed-4d7d-a97f-8759cdff3849">

2024-03-07 18:23 UTC, maxim2310 approved these changes
Well done!!!

2025-03-11 20:31 UTC, closed without merging