implemented
mate-academy/react_movies-list-add-form pull request #2297
Opened 2024-04-12 12:52 UTC by DanielLinker17

https://DanielLinker17.github.io/react_movies-list-add-form/

2024-04-12 13:13 UTC, anastasiiavorobiova requested changes
Great work! Almost done!

2024-04-12 13:13 UTC, anastasiiavorobiova commented on src/components/NewMovie/NewMovie.tsx
> +  // #region state
```suggestion
  // #region state
  const [movie, setMovie] = useState({
    title: '',
    description: '',
    ...
  })
```

2024-04-12 13:13 UTC, anastasiiavorobiova commented on src/components/NewMovie/NewMovie.tsx
> +  const [imdbId, setImdbId] = useState('');
```suggestion

```

2024-04-12 13:13 UTC, anastasiiavorobiova commented on src/components/NewMovie/NewMovie.tsx
> +  };
```suggestion

```

2024-04-12 13:13 UTC, anastasiiavorobiova commented on src/components/NewMovie/NewMovie.tsx
> +  };
```suggestion
  const handleChange = (event: ...) => {
    setMovie(movie => ({
      ...movie,
      [event.target.name]: event.target.value
    }));
  };
```

2024-04-12 13:13 UTC, anastasiiavorobiova commented on src/components/NewMovie/NewMovie.tsx
> +        onChange={handleTitleChange}
```suggestion
        onChange={handleChange}
```

2024-04-12 13:13 UTC, anastasiiavorobiova commented on src/components/NewMovie/NewMovie.tsx
> +        onChange={handleDescriptionChange}
```suggestion
        onChange={handleChange}
```

2024-04-12 13:13 UTC, anastasiiavorobiova commented on src/components/NewMovie/NewMovie.tsx
> +        onChange={handleImgUrlChange}
```suggestion
        onChange={handleChange}
```

2024-04-12 13:13 UTC, anastasiiavorobiova commented on src/components/NewMovie/NewMovie.tsx
> +        onChange={handleImdbUrlChange}
```suggestion
        onChange={handleChange}
```

2024-04-12 13:13 UTC, anastasiiavorobiova commented on src/components/NewMovie/NewMovie.tsx
> +        onChange={handleImdbIdChange}
```suggestion
        onChange={handleChange}
```

2024-04-12 13:14 UTC, anastasiiavorobiova requested changes
<img width="332" alt="Screenshot 2024-04-12 at 16 08 57" src="https://github.com/mate-academy/react_movies-list-add-form/assets/135232001/f478eb70-d68f-43e9-9b82-1f61342aefce">
Also, consider keeping the button disabled when there are just spaces

2024-04-15 14:50 UTC, anastasiiavorobiova requested changes
Great work! Almost done!

2024-04-15 14:50 UTC, anastasiiavorobiova commented on src/components/NewMovie/NewMovie.tsx
> +        onChange={newValue => handleChange('title', newValue)}
```suggestion
        onChange={handleChange}
```
Consider reusing just one function that accepts the event object instead of creating 5 different functions

2024-04-15 14:50 UTC, anastasiiavorobiova commented on src/components/NewMovie/NewMovie.tsx
> +  const handleChange = (name: string, newValue: string) => {
```suggestion
  const handleChange = (event) => {
```

2024-04-15 14:50 UTC, anastasiiavorobiova commented on src/components/NewMovie/NewMovie.tsx
> +      [name]: newValue,
```suggestion
      [event.target.name]: event.target.value,
```

2024-04-15 20:42 UTC, VitaliyBondarenko1982 approved these changes
Good job.

2024-04-15 20:42 UTC, VitaliyBondarenko1982 commented on src/components/TextField/TextField.tsx
>    const hasError = touched && required && !value;
```suggestion
  const hasError = touched && required && !value.trim();
```
filled all inputs only with empty space.
any errors visible, but add button still disabled.

better to trim value for hasError variable.
![Screenshot 2024-04-15 at 23 39 27](https://github.com/mate-academy/react_movies-list-add-form/assets/33029864/c4532066-46b4-4d78-b3b9-b85f84e6d9e4)

2025-07-29 00:37 UTC, closed without merging