solution
mate-academy/react_movies-list-add-form pull request #237
Opened 2021-03-29 12:12 UTC by Jastler

[DEMO LINK](https://jastler.github.io/react_movies-list-add-form/index.html)

2021-03-31 07:01 UTC, vitaliiskr approved these changes

2021-03-31 12:06 UTC, Vladimir-Beliy approved these changes

2021-03-31 12:06 UTC, Vladimir-Beliy commented on src/components/NewMovie/NewMovie.js
> +  }
switch case

2021-03-31 12:06 UTC, Vladimir-Beliy requested changes
\

2021-04-02 13:46 UTC, Vladimir-Beliy requested changes

2021-04-02 13:46 UTC, Vladimir-Beliy commented on src/components/NewMovie/NewMovie.js
> +        }
```suggestion
          this.setState({
            [`is${name[0].toUpperCase() + name.slice(1)}`]: validateUrl(value),
            [name]: value,
          });
        }
```

2021-04-06 12:51 UTC, solaryasha approved these changes

2026-05-12 17:04 UTC, closed without merging