solution
mate-academy/react_movies-list-add-form pull request #2525
Opened 2024-09-09 09:56 UTC by Natallia3105

https://Natallia3105/react_movies-list-add-form.github.io/react_movies-list-add-form/

2024-09-09 11:13 UTC, volodymyr-soltys97 requested changes
Hi, the demo link is wrong now 
<img width="854" alt="image" src="https://github.com/user-attachments/assets/0fbfe551-9a13-499f-8489-ec0fbe333550">

2024-09-09 11:13 UTC, volodymyr-soltys97 commented on src/components/NewMovie/NewMovie.tsx
> +  const [imdbId, setImdbId]= useState('');
Сreate only one state for movie
```suggestion
  const [movie, setMovie] = useState({
    title: '',
    .......
  });
```

2024-09-09 11:41 UTC, Natallia3105 commented
<img width="1037" alt="Screenshot 2024-09-09 at 14 36 08" src="https://github.com/user-attachments/assets/aab4d887-ee8a-4126-b98f-bf4d899cb81a">
<img width="1424" alt="Screenshot 2024-09-09 at 14 36 56" src="https://github.com/user-attachments/assets/d729bbf4-1753-485d-8fd4-482e17cbd06e">


file:///Users/natalagoncaruk/projects/react_movies-list-add-form/reports/report.html - tests

2024-09-09 12:40 UTC, anastasiiavorobiova requested changes
The demo link isn't reachable 
<img width="1048" alt="Screenshot 2024-09-09 at 15 39 27" src="https://github.com/user-attachments/assets/4cd2c0ae-d2b8-4a52-871f-9c95e918de42">

2024-09-10 08:20 UTC, Natallia3105 commented
https://natallia3105.github.io/react_movies-list-add-form/

2024-09-10 08:44 UTC, etojeDenys approved these changes

2025-01-24 13:17 UTC, closed without merging