solution
mate-academy/react_movies-list-add-form pull request #2557
Opened 2024-10-04 11:46 UTC by coldmelnyk

[DEMO LINK](https://coldmelnyk.github.io/react_movies-list-add-form/)

2024-10-04 14:49 UTC, PikalovAndrey commented
<img width="385" alt="image" src="https://github.com/user-attachments/assets/5f2cd273-9d09-4fb3-8145-a543317e1975">

The photo shows that a description is required, but the form can be submitted without it. This really doesn't make sense.

2024-10-04 14:50 UTC, PikalovAndrey approved these changes
Good work!

2024-10-07 09:47 UTC, igorkruz requested changes
Good Job 👍
Review all task requirements and fix your solution

![Screenshot 2024-10-07 122742](https://github.com/user-attachments/assets/388d5057-0245-4b05-bfe3-d90b82a00151)

https://www.loom.com/share/9394b090beb24c6387fc823854f7f4f0?sid=28b085dd-2983-449f-9dfa-f7098cf04691

2024-10-07 09:47 UTC, igorkruz commented on src/components/NewMovie/NewMovie.tsx
> +  const [imbdId, setImbdId] = useState('');
It's better to use a single state object for all values, simplifies state management and reduces code complexity. It also minimizes unnecessary re-renders, as updating multiple values in one object triggers only one re-render.
```suggestion
  const [formData, setFormData] = useState({
    description: '',
    title: '',
    imgUrl: '',
    imdbUrl: '',
    imdbId: ''
  });
```

2024-10-07 09:47 UTC, igorkruz commented on src/components/NewMovie/NewMovie.tsx
> +    };
You can shorten it by using shorthand property names, as the object keys and variable names are the same
```suggestion
    const newMovieToPush: Movie = {
      title,
      description,
      imgUrl,
      imdbUrl,
      imdbId,
    };
```

2024-10-07 09:47 UTC, igorkruz commented on src/components/NewMovie/NewMovie.tsx
> +          )}
You can render just one button with a conditional disabled attribute, it simplifies the code, reduces repetition, and improves maintainability.
```suggestion
          <button
             type="submit"
             data-cy="submit-button"
             className="button is-link"
             disabled={!isFormFull}
           >
              Add
           </button>
```

2024-10-21 11:00 UTC, igorkruz approved these changes
Great job 👍 
Please consider the additional comments.

2024-10-21 11:00 UTC, igorkruz commented on src/components/NewMovie/NewMovie.tsx
> +        }
create a handle function for this logic

2025-07-18 21:51 UTC, closed without merging