Solution
mate-academy/react_movies-list-add-form pull request #292
Opened 2021-05-30 15:23 UTC by igor-stasiv

[DEMO LINK](https://igor-stasiv.github.io/react_movies-list-add-form/)

2021-05-31 09:29 UTC, Burunduk003 approved these changes
If you disable the button before the user even tries to enter data, he or she cant see an error message. They didn't know what fields are required, so they can consider your site is broken and the button didn't work in any cases.

2021-05-31 09:29 UTC, Burunduk003 commented on src/components/NewMovie/NewMovie.jsx
> +        </p>
in what cases this message will appear?

2021-05-31 10:02 UTC, igor-stasiv commented on src/components/NewMovie/NewMovie.jsx
> +        </p>
I was thinking that the class name `active` is enough for understanding. I meant that if an error is then the message will be active. But maybe there will be better used just conditional rendering without `classNames`

2021-05-31 13:48 UTC, aliceblunt8 requested changes

2021-05-31 13:48 UTC, aliceblunt8 commented on src/components/NewMovie/NewMovie.jsx
> +  }
hmm why do you need this?

2021-05-31 13:48 UTC, aliceblunt8 commented on src/components/NewMovie/NewMovie.jsx
> +        }));
leave only cases with imgUrl and imdbUrl here, all other cases should be processed in default case

2021-05-31 13:48 UTC, aliceblunt8 commented on src/components/NewMovie/NewMovie.jsx
> +    };
```suggestion
    const { onAdd } = this.props;
    
    const {
      title,
      description,
      imgUrl,
      imdbUrl,
      imdbId,
    } = this.state;
    
    const isError = {
      title: !title.trim(),
      imgUrl: !urlValidation.test(imgUrl),
      imdbUrl: !urlValidation.test(imdbUrl),
      imdbId: !imdbId.trim(),
    };
```

2021-05-31 14:10 UTC, igor-stasiv commented on src/components/NewMovie/NewMovie.jsx
> +  }
I use it for reset form fields

2021-05-31 14:13 UTC, igor-stasiv commented on src/components/NewMovie/NewMovie.jsx
> +        }));
I can't do it, because I don't need to check errors of the `description` field, so `description` is default case

2021-05-31 14:46 UTC, aliceblunt8 commented on src/components/NewMovie/NewMovie.jsx
> +  }
you can do event.target.reset() inside handleSubmit function instead of this

2021-05-31 14:46 UTC, aliceblunt8 requested changes
I left comments

2021-05-31 15:12 UTC, igor-stasiv commented on src/components/NewMovie/NewMovie.jsx
> +  }
it doesn't work

2021-06-01 07:49 UTC, aliceblunt8 approved these changes

2024-12-15 15:23 UTC, closed without merging