Add form implemented
mate-academy/react_movies-list-add-form pull request #366
Opened 2021-07-30 15:04 UTC by andrii-balitskyi

[DEMO LINK](https://andrii-balitskyi.github.io/react_movies-list-add-form/)

2021-08-01 22:16 UTC, Vivdyuk approved these changes
GJ! Але, як на мене, трохи оверкілиш

2021-08-01 22:16 UTC, Vivdyuk commented on src/App.js
> +  addMovie = (title, description, imgUrl, imdbUrl, imdbId) => {
А члому б просто не приймати об'єкт movie?

2021-08-01 22:16 UTC, Vivdyuk commented on src/App.js
> +    };
По суті, overkill

2021-08-02 08:25 UTC, ArtemTopolskyi requested changes

2021-08-02 08:25 UTC, ArtemTopolskyi commented on src/App.js
>    };
каждая функция должна выполнять только одно действие: в твоем же случае она и создает фильм, и добавляет его в массив. Вынеси создание в отдельную функцию, а в этой принимай объект movie

2021-08-02 08:25 UTC, ArtemTopolskyi commented on src/components/NewMovie/NewMovie.js
> +    });
вынеси это в отдельную функцию "clearForm"

2021-08-02 11:53 UTC, ArtemTopolskyi approved these changes

2021-08-02 11:53 UTC, ArtemTopolskyi commented on src/App.js
> +    };
этот метод не использует state этого компонента, зачем его объявлять здесь? Объяви в NewMovie и  не надо будет его прокидывать вниз

2024-04-05 13:08 UTC, closed without merging