Done
mate-academy/react_movies-list-add-form pull request #569
Opened 2022-01-27 02:10 UTC by MaksimusCRS

[DEMO LINK](https://MaksimusCRS.github.io/react_movies-list-add-form/)

2022-01-27 07:25 UTC, Oleksandr-Leshchenko requested changes

2022-01-27 07:25 UTC, Oleksandr-Leshchenko commented on src/components/NewMovie/NewMovie.tsx
> +        </div>
Не, ну это страх, конечно. А если бы инпутов было 50, то шоб ты делал?)

2022-01-27 07:25 UTC, Oleksandr-Leshchenko commented on src/components/NewMovie/NewMovie.tsx
> +        </div>
Плюс там не должно быть никаких имейлов. У тебя ссылки

2022-01-27 07:46 UTC, Oleksandr-Leshchenko approved these changes

2022-02-01 08:49 UTC, Elena-brv approved these changes

2022-02-01 08:49 UTC, Elena-brv commented on src/components/NewMovie/NewMovie.tsx
> +interface State {
```suggestion
};

interface State {
```

2022-02-01 08:49 UTC, Elena-brv commented on src/components/NewMovie/NewMovie.tsx
> +    }));
```suggestion
    this.setState(state => ({
      [event.target.name]: event.target.value,
    }));
```

2022-02-01 08:49 UTC, Elena-brv commented on src/components/NewMovie/NewMovie.tsx
> +      title: '',
```suggestion
    event.preventDefault();
    
    this.props.onAdd(this.state);
    
    this.setState({
      title: '',
```

2022-10-20 17:44 UTC, closed without merging