whew
mate-academy/react_movies-list-add-form pull request #614
Opened 2022-02-23 10:59 UTC by trtskvalerie

[DEMO LINK](https://trtskvalerie.github.io/react_movies-list-add-form/)

2022-02-23 11:28 UTC, tvoyammn requested changes
ойойой ну давай работай дальше

2022-02-23 11:28 UTC, tvoyammn commented on src/components/NewMovie/NewMovie.tsx
> +
себе на dirty провєріть не забула?

2022-02-23 11:28 UTC, tvoyammn commented on src/components/NewMovie/NewMovie.tsx
> +      }}
це в отдєльну функцию хендлєр

2022-02-23 11:28 UTC, tvoyammn commented on src/components/NewMovie/NewMovie.tsx
> +        />
по настроєнію
```suggestion
          onChange={(event) => setDescription(event.target.value);}
        />
```

2022-02-23 11:28 UTC, tvoyammn commented on src/components/NewMovie/NewMovie.tsx
> +        />
ціє блюри всє тоже винести не помєшало б, вельми вони великіє

2022-02-23 13:08 UTC, tvoyammn approved these changes
просто потрясающє

2022-02-23 13:08 UTC, tvoyammn commented on src/components/NewMovie/NewMovie.tsx
> +    setImdbIdIsDirty(false);
нікуда не спішим

2022-02-23 13:45 UTC, OleksiiBlezniuk requested changes

2022-02-23 13:45 UTC, OleksiiBlezniuk commented on src/components/NewMovie/NewMovie.tsx
> +  const [imdbIdIsDirty, setImdbIdIsDirty] = useState(false);
Может просто устанавливать ошибку на onBlur? Думаю без этих стейтов обойтись

2022-02-23 13:45 UTC, OleksiiBlezniuk commented on src/components/NewMovie/NewMovie.tsx
> +    setImdbIdIsInvalid(true);
Лучше бы вынести в отдельную функцию  reset

2022-03-14 08:36 UTC, Elena-brv approved these changes

2022-03-14 08:36 UTC, Elena-brv commented on src/App.tsx
> +        />
```suggestion
        <NewMovie onAdd={addMovie} />
```

2022-03-14 08:36 UTC, Elena-brv commented on src/components/NewMovie/NewMovie.tsx
> +import './NewMovie.scss';
```suggestion
import React, { useState } from 'react';
import './NewMovie.scss';
```

2022-03-14 08:36 UTC, Elena-brv commented on src/components/NewMovie/NewMovie.tsx
> +  imdbId: boolean,
if it's boolean, variables should also look like boolean. eg. `isTitleEmpty`

2022-03-14 08:36 UTC, Elena-brv commented on src/components/NewMovie/NewMovie.tsx
> +  const [isDirty, setIsDirty] = useState({
```suggestion
  const [isFilledIn, setIsFilledIn] = useState({
```

2022-03-14 08:36 UTC, Elena-brv commented on src/components/NewMovie/NewMovie.tsx
> +    onAdd(newMovie);
```suggestion
    onAdd(newMovie);
    resetForm();
```

2022-03-14 08:36 UTC, Elena-brv commented on src/components/NewMovie/NewMovie.tsx
> +            setTitle(event.target.value);
you can create a common function for all inputs

2024-03-17 12:14 UTC, closed without merging