first solution
mate-academy/react_movies-list-add-form pull request #638
Opened 2022-03-30 10:51 UTC by SanyaBratashchuk

https://SanyaBratashchuk.github.io/react_movies-list-add-form/

2022-04-01 12:24 UTC, solaryasha requested changes

2022-04-01 12:24 UTC, solaryasha commented on src/components/Input/Input.tsx
> +export const Input: React.FC<Props> = ({
react.memo

2022-04-01 12:24 UTC, solaryasha commented on src/components/NewMovie/NewMovie.tsx
> +  state: State = {
Давай хуки попрактикуємо

2022-04-04 12:32 UTC, Ihor-Karpyn approved these changes

2026-05-02 10:22 UTC, closed without merging