first part of the task
mate-academy/react_movies-list-add-form pull request #659
Opened 2022-04-08 18:56 UTC by AnnSerdechna

[Demo](https://annserdechna.github.io/react_movies-list-add-form/)

2022-04-11 09:55 UTC, RomanKushyk approved these changes
great work!

2022-04-11 09:55 UTC, RomanKushyk commented on src/App.tsx
> +  }, []);
🤔

2022-04-11 10:32 UTC, solaryasha requested changes

2022-04-11 10:32 UTC, solaryasha commented on src/App.tsx
> +    imdbId: string,
Простіше передати об'єкт

2022-04-11 10:32 UTC, solaryasha commented on src/App.tsx
> +  }, []);
Навіщо це потрібно ?

2022-04-11 10:32 UTC, solaryasha commented on src/components/NewMovie/NewMovie.scss
> +}
Уникай стилізації тегів

2022-04-11 10:32 UTC, solaryasha commented on src/components/NewMovie/NewMovie.tsx
> +  const handleSubmit = (e: React.SyntheticEvent) => {
Не скорочуй назви змінних

2022-04-11 10:32 UTC, solaryasha commented on src/components/NewMovie/NewMovie.tsx
> +        onChange={(e: React.ChangeEvent<HTMLInputElement>) => setTitle(e.target.value)}
```suggestion
        onChange={(event: React.ChangeEvent<HTMLInputElement>) => setTitle(e.target.value)}
```

2022-04-11 10:32 UTC, solaryasha commented on src/components/NewMovie/NewMovie.tsx
> +        onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
```suggestion
        onChange={(event: React.ChangeEvent<HTMLInputElement>) => {
```

2022-04-11 10:32 UTC, solaryasha commented on src/components/UI/Input/Input.tsx
> +      // onBlur={onBlur}
Не залишай коментарі

2022-04-11 10:32 UTC, solaryasha commented on src/components/UI/Button/Button.tsx
> +  children: any;
Children можеш не описувати

2022-04-11 10:32 UTC, solaryasha commented on src/components/UI/Input/Input.tsx
> +  onChange: (e: any) => void;
event можеш описати React.ChangeEvent<HTMLInputElement>

2022-04-11 10:32 UTC, solaryasha commented on src/components/UI/Input/Input.tsx
> +export const Input: FC<Props> = ({
Use react.memo

2022-04-12 14:41 UTC, solaryasha approved these changes

2022-04-12 14:41 UTC, solaryasha commented on src/App.tsx
> +    setMovies((prev) => ([
Не скорочуй назви змінних
```suggestion
    setMovies((prevMovies) => ([
```

2024-12-05 14:38 UTC, closed without merging