react_movies-list-add-form
mate-academy/react_movies-list-add-form pull request #664
Opened 2022-04-11 12:48 UTC by IvanShulhan

[DEMO LINK](https://ivanshulhan.github.io/react_movies-list-add-form/)

2022-04-11 14:33 UTC, ArturErmolenko requested changes
Add Demo Link or Readme file

2022-04-12 20:59 UTC, marina-tilniak requested changes

2022-04-12 20:59 UTC, marina-tilniak commented on src/components/NewMovie/NewMovie.tsx
> +        }}
move to separate function

2022-04-12 20:59 UTC, marina-tilniak commented on src/components/NewMovie/NewMovie.tsx
> +      && isUrlValid(imdbUrl) && isTextValid(imdbId);
move this check into submit handler

2022-04-13 19:33 UTC, ArturErmolenko approved these changes

2024-10-20 10:18 UTC, closed without merging