solution
mate-academy/react_movies-list-add-form pull request #733
Opened 2022-06-10 23:05 UTC by yelnikov-andrii

[DEMO LINK](https://yelnikov-andrii.github.io/react_movies-list-add-form/)

2022-06-11 15:36 UTC, vlasiuk-anatolii approved these changes
The last field in form was dublicated. There is have not field "imdbId"

2022-06-14 12:10 UTC, Anna-Tkachenko requested changes

2022-06-14 12:10 UTC, Anna-Tkachenko commented on src/components/NewMovie/NewMovie.tsx
> +        return 'The wrong URL';
Not all inputs should have this error
For example, title shouldn't be the url
<img width="401" alt="image" src="https://user-images.githubusercontent.com/30314756/173573847-ec1780e4-9407-4b0b-9bc4-456a720f8fea.png">

2022-06-15 12:51 UTC, yelnikov-andrii commented
> I can't add movie, fix it

why? I can add movie

2022-06-16 11:54 UTC, Anna-Tkachenko approved these changes

2022-06-16 11:54 UTC, Anna-Tkachenko commented on src/components/NewMovie/NewMovie.tsx
> +  const [buttonDisabled, setButtonDisabled] = useState(false);
Will be better to use boolean values here instead of string

2022-06-16 11:54 UTC, Anna-Tkachenko commented on src/components/NewMovie/NewMovie.tsx
> +          }
You repeat this code many times, will be better to create separate function for it

2024-03-19 15:11 UTC, closed without merging