React movies list add form
mate-academy/react_movies-list-add-form pull request #781
Opened 2022-07-14 14:44 UTC by vsupruniuk

[DEMO LINK](https://vsupruniuk.github.io/react_movies-list-add-form/)

Pay attention that the regular expression does not allow any images from IMDb however, allow the image from the file `movies.json`

2022-07-18 10:52 UTC, jstmpelowycz requested changes

2022-07-18 10:52 UTC, jstmpelowycz commented on src/components/NewMovie/NewMovie.tsx
> +    }
you could combine them

2022-07-18 10:52 UTC, jstmpelowycz commented on src/components/NewMovie/NewMovie.tsx
> +    }
here, too

2022-07-19 07:48 UTC, illiarerun requested changes

2022-07-19 07:48 UTC, illiarerun commented on .env
> +DISABLE_ESLINT_PLUGIN = true
what's that?)
```suggestion
```

2022-07-20 13:33 UTC, illiarerun approved these changes

2024-01-28 12:19 UTC, closed without merging