solution
mate-academy/react_movies-list-add-form pull request #782
Opened 2022-07-15 10:07 UTC by kostya-konev

[DEMO LINK](https://kostya-konev.github.io/react_movies-list-add-form/)

2022-07-15 10:09 UTC, kostya-konev commented
Задеплоить не получилось. Появляется ошибка с 
<img width="1440" alt="Screenshot 2022-07-15 at 13 08 40" src="https://user-images.githubusercontent.com/36968441/179202762-bb165308-355f-4a82-9416-42ca2ab19b7d.png">
eslint.

2022-07-15 10:11 UTC, kostya-konev commented
![Uploading Screenshot 2022-07-15 at 12.59.06.png…]()

2022-07-19 10:48 UTC, marina-tilniak requested changes
не всі файли додані на GitHub

2022-09-12 13:20 UTC, kostya-konev commented
<img width="1440" alt="Снимок экрана 2022-09-12 в 16 04 18" src="https://user-images.githubusercontent.com/36968441/189664931-c2f8f280-f749-492d-b8fa-4215f44e1e4a.png">
<img width="1440" alt="Снимок экрана 2022-09-12 в 16 05 49" src="https://user-images.githubusercontent.com/36968441/189664945-8eddef11-4b33-4af8-b1c2-70add1f487d3.png">

2022-09-13 18:34 UTC, SanyaBratashchuk requested changes

2022-09-13 18:34 UTC, SanyaBratashchuk commented on src/App.tsx
> +    setMovies([...movies, movie]);
Нема перевірки на дублікати

2022-09-28 09:14 UTC, kostya-konev commented on src/App.tsx
> +    setMovies([...movies, movie]);
Супер. Цього в завданнi не було!

2022-09-28 10:04 UTC, kostya-konev commented on src/App.tsx
> +    setMovies([...movies, movie]);
Done ✅

2023-09-12 13:51 UTC, closed without merging