add form movie
mate-academy/react_movies-list-add-form pull request #803
Opened 2022-07-21 19:01 UTC by KrisMur

[DEMO LINK](https://KrisMur.github.io/react_movies-list-add-form/)

2022-07-22 08:14 UTC, ostapfriend approved these changes
Робота супер. Класно реалізувала кнопку, щоб коли поля були незаповнені, вона була недоступна)

2022-07-22 08:14 UTC, ostapfriend commented on src/App.tsx
> +          <NewMovie
Думаю, якщо один параметр передаєш, можна все в один рядок писати. P.S мені так сказали також, так як виходить 3 рядки коду замість 1

2022-07-22 09:52 UTC, jstmpelowycz requested changes

2022-07-22 09:52 UTC, jstmpelowycz commented on src/App.tsx
> +          />
```suggestion
          <NewMovie submitMovie={this.addMovie}  />
```

2022-07-22 09:52 UTC, jstmpelowycz commented on src/components/NewMovie/NewMovie.tsx
> +const clearMovieForm: Movie = {
```suggestion
const clearMovieFormFields: Movie = {
```

2022-07-22 09:52 UTC, jstmpelowycz commented on src/components/NewMovie/NewMovie.tsx
> +  const [isBtnDisabled, setIsBtnDisabled] = useState<boolean>(true);
```suggestion
  const [isBtnDisabled, setIsBtnDisabled] = useState(true);
```

2022-07-22 09:52 UTC, jstmpelowycz commented on src/components/NewMovie/NewMovie.tsx
> +    }
```suggestion
    const shouldDisableButton =  (
      !title || !imgUrl || !imdbUrl || !imdbId
    );
    
    setIsBtnDisabled(shouldDisableButton);
```

2022-07-22 09:52 UTC, jstmpelowycz commented on src/components/NewMovie/NewMovie.tsx
> +        break;
create enum instead

2022-07-22 09:52 UTC, jstmpelowycz commented on src/components/NewMovie/NewMovie.tsx
> +  useEffect(checkBtnDisable);
`useEffect` should consist of two parts – callback + deps array (don't forget about this array)
thus, first of all, add a deps array
```
useEffect(() => {
  checkButtonDisable();
}, [...]);
```

2022-07-26 09:14 UTC, Olexandr6 approved these changes

2024-10-19 12:31 UTC, closed without merging