solution
mate-academy/react_movies-list-add-form pull request #993
Opened 2022-10-12 07:33 UTC by ihorandrianov

[DEMO LINK](https://ihorandrianov.github.io/react_movies-list-add-form/)

2022-10-13 16:35 UTC, naziamoff requested changes
- You should clear the form fields after the submit
- I can add one movie a lot of times, you should validate it
- I can put two spaces as a movie name. You should handle this too

2022-10-24 19:51 UTC, Denchepornyuk approved these changes

2022-10-24 19:51 UTC, Denchepornyuk commented on src/App.tsx
> +      newState.push(movie);
don't use push, add movie with array copy

2022-10-24 19:51 UTC, Denchepornyuk commented on src/components/Button.tsx
> +  const ctx = useFormikContext<Movie>();
🔥

2022-10-24 19:51 UTC, Denchepornyuk commented on src/components/NewMovie/NewMovie.tsx
> +    >
I didn't work with formik, we use React Final Form in Mate but it looks great 🚀

2023-05-05 06:05 UTC, naziamoff approved these changes

2023-10-31 12:07 UTC, closed without merging